baseURL: https://co-analysis.github.io/govuk-hugo-demo/
languageCode: en-gb
title: govuk-hugo Demonstration
theme: govukhugo
publishDir: docs
canonifyurls: false

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2


params:
  govuk: false
  logotext: GHD
  product: Demonstration and Documentation of govuk-hugo
  phase: alpha
  feedbackurl: https://github.com/co-analysis/govuk-hugo-demo/issues/
  accessibility: accessibility.md
  cookies: cookies.md
  builtby: "Cabinet Office Analysis & Insight"
  builtbyurl: https://www.github.com/co-analysis